PUT http://localhost:3003/api/blogs/64186757aeaa6937683b4839
Content-Type: application/json

{
"title": "Blog 1.1", "author": "Thanki Ajay", "url": "/blog-1.1", "likes": "50"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
"title": "Blog 1", "author": "Ajay Thanki", "url": "/blog-1", "likes": "150"
}

###
GET http://localhost:3003/api/blogs
###

DELETE http://localhost:3003/api/blogs/64186746aeaa6937683b4835